title: Jenna Kang
position: Ph.D. Student
affiliation: New York University
email: jennakang@nyu.edu
undergrad_affiliation: B.S. in CS @ Georgia Institute of Technology
# keywords:  
# google_scholar: https://scholar.google.com/
github_link: https://github.com/jennakangg
instagram_link: https://instagram.com/jenjenzies
linkedin: https://www.linkedin.com/in/jennakangg/
avatar: ./assets/img/personal_image.jpeg
NYU_img: ./assets/img/NYU.png
GT_img: ./assets/img/GT.png
google_analytics: UA-111540567-4
favicon: ./assets/img/MF.jpg
favicon_dark: ./assets/img/MF.jpg
description: Jenna Kang
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
