title: Jenna Kang
position: Ph.D. Student
affiliation: New York University
email: jkang394@gatech.edu
# keywords:  
# google_scholar: https://scholar.google.com/
# github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/jennajkang/
avatar: ./assets/img/personal_image.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/MF.jpg
favicon_dark: ./assets/img/MF.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
